[package]
name = "aurelius"
version = "0.6.0"
authors = ["Andy Russell <arussell123@gmail.com>"]
documentation = "https://euclio.github.io/aurelius"
homepage = "https://github.com/euclio/aurelius"
keywords = ["markdown", "vim"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/euclio/aurelius"
description = "A complete solution for previewing markdown."

[dependencies]
chan = "0.1.14"
error-chain = "0.11"
handlebars-iron = "0.26"
iron = "0.6"
lazy_static = "1"
log = "0.4"
mount = "0.4"
pulldown-cmark = { git = "https://github.com/matthewmazzanti/pulldown-cmark.git", default-features = false }
serde = "1"
serde_derive = "1"
staticfile = "0.5"
url = "1.1.0"
websocket = { version = "0.20", default-features = false, features = ["sync"] }

[dev-dependencies]
reqwest = "0.8"
iron-test = "0.6"
